"""Agent Registry — the 31 pharma agents from Agent.md as runnable definitions.

Each agent binds a goal + reasoning framework + a concrete set of registered
tools. ME (Manufacturing Execution) and QA (Quality) are the deep vertical slice
(depth='full'); the rest are fully catalogued and runnable with real tools.

GxP guardrail (Agent.md §2): agents may RECOMMEND but never autonomously release
product, approve batch records, or close deviations without human e-signature.
"""
from __future__ import annotations

DOMAINS = {
    "SCP": {"name": "Supply Chain & Procurement", "color": "#2563eb",
            "goal": "Raw Material Availability >= 98% | Supplier Quality >= 85"},
    "WM": {"name": "Warehouse & Material Mgmt", "color": "#16a34a",
           "goal": "Dispensing Accuracy 100% | Inventory Accuracy >= 99%"},
    "ME": {"name": "Manufacturing Execution", "color": "#ea580c",
           "goal": "Batch Success >= 98% | Right-First-Time >= 95%"},
    "QA": {"name": "Quality Control & Assurance", "color": "#9333ea",
           "goal": "Right-First-Time >= 95% | OOS Rate <= 0.5%"},
    "EQ": {"name": "Equipment & Compliance Mgmt", "color": "#0891b2",
           "goal": "Qualified Availability >= 95% | Calibration 100%"},
    "REG": {"name": "EHS, Regulatory & PV", "color": "#65a30d",
            "goal": "Regulatory Compliance 100% | PV Signal Review <= 15 days"},
}

FRAMEWORKS = {
    "ReAct": "Reason -> Act -> Observe -> Repeat",
    "Plan-and-Execute": "Plan -> decompose -> Execute -> Validate",
    "OODA": "Observe -> Orient -> Decide -> Act",
    "Tree-of-Thought": "Generate hypotheses -> branch -> score -> prune -> synthesise",
    "Generate-Critique-Revise": "Generate -> Critique -> Revise -> Publish",
    "Reflect-and-Correct": "Generate -> Critique -> Correct -> Audit",
}

AGENTS: list[dict] = [
    # ------------------------------------------------- Supply Chain & Procurement
    {"id": "SCP-001", "name": "Raw Material Planning Agent", "domain": "SCP",
     "framework": "Plan-and-Execute", "depth": "catalog",
     "goal": "Generate material requirements from production schedules, manage reorder points, and prevent shortages that delay batch manufacture.",
     "triggers": ["MPS updated", "Daily 01:00 MRP", "Stock below reorder point", "API shelf-life warning"],
     "tools": ["material_availability_tool", "material_shortage_scan", "supplier_query_tool",
               "pharma_alert_tool", "audit_trail_tool"],
     "escalation": "API shortage within 30 days -> Supply Chain Manager + QP",
     "sends_to": ["SCP-002"], "receives_from": ["SCP-005", "WM-P01"]},
    {"id": "SCP-002", "name": "Purchase Order Agent", "domain": "SCP",
     "framework": "ReAct", "depth": "catalog",
     "goal": "Convert approved requisitions into GMP purchase orders, track deliveries and quality documents (CoA/CoC/DMF).",
     "triggers": ["Approved PR from SCP-001", "Delivery date lapsed", "Missing CoA alert"],
     "tools": ["supplier_query_tool", "coa_review_tool", "pharma_alert_tool", "audit_trail_tool"],
     "escalation": "Critical material delayed >5 days -> Supply Chain Manager",
     "sends_to": ["WM-P01", "SCP-003"], "receives_from": ["SCP-001"]},
    {"id": "SCP-003", "name": "Supplier Qualification & Performance Agent", "domain": "SCP",
     "framework": "Reflect-and-Correct", "depth": "catalog",
     "goal": "Maintain the Approved Supplier List by scoring qualification, performance, and audit status; flag at-risk suppliers early.",
     "triggers": ["Quarterly audit", "Incoming OOS", "GMP cert expiring", "Monthly performance calc"],
     "tools": ["supplier_scorecard_tool", "coa_review_tool", "supplier_query_tool",
               "report_generator_tool", "pharma_alert_tool"],
     "escalation": "Supplier suspension -> QP + VP Quality + Legal",
     "sends_to": ["SCP-001", "REG-P03"], "receives_from": ["QA-P02"]},
    {"id": "SCP-004", "name": "Cold Chain Logistics Agent", "domain": "SCP",
     "framework": "ReAct", "depth": "catalog",
     "goal": "Monitor temperature-sensitive shipments, detect transit excursions, and coordinate QA impact evaluation before acceptance.",
     "triggers": ["Logger data received", "Excursion threshold crossed", "Shipment arrival"],
     "tools": ["em_result_query", "pharma_alert_tool", "audit_trail_tool"],
     "escalation": "Significant excursion on API -> QA Director + Regulatory Affairs",
     "sends_to": ["WM-P01", "QA-P02"], "receives_from": []},
    {"id": "SCP-005", "name": "Demand Forecasting Agent", "domain": "SCP",
     "framework": "Generate-Critique-Revise", "depth": "catalog",
     "goal": "Generate rolling 18-month demand forecasts integrating orders, market signals, and regulatory events.",
     "triggers": ["Weekly Monday 02:00", "New approval", "Market withdrawal", "Q4 plan cycle"],
     "tools": ["report_generator_tool", "signal_detection_tool"],
     "escalation": "Drug shortage risk (demand > capacity >3 months) -> VP Operations",
     "sends_to": ["SCP-001", "ME-P01"], "receives_from": ["REG-P03"]},

    # --------------------------------------------- Warehouse & Material Management
    {"id": "WM-P01", "name": "Inventory & Quarantine Agent", "domain": "WM",
     "framework": "ReAct", "depth": "catalog",
     "goal": "Manage material lifecycle quarantine->release->dispensing, enforce FEFO, and block unapproved material from manufacture.",
     "triggers": ["Goods receipt posted", "QC release/reject", "Expiry within 30 days", "Batch requires material"],
     "tools": ["material_availability_tool", "material_shortage_scan",
               "material_status_update_tool", "pharma_alert_tool"],
     "escalation": "Rejected critical material with no approved stock -> QP + Supply Chain",
     "sends_to": ["WM-P02", "WM-P03", "SCP-001"], "receives_from": ["SCP-002"]},
    {"id": "WM-P02", "name": "Sampling Coordination Agent", "domain": "WM",
     "framework": "Plan-and-Execute", "depth": "catalog",
     "goal": "Coordinate sampling of incoming materials per approved plans, track sample transport, and ensure testing within SLA.",
     "triggers": ["New quarantine GRN", "Sampling schedule due", "Overdue test alert"],
     "tools": ["material_availability_tool", "analytical_result_query", "pharma_alert_tool"],
     "escalation": "Sample overdue >3 days on critical raw material -> QC Manager",
     "sends_to": ["QA-P01", "WM-P01"], "receives_from": ["WM-P01"]},
    {"id": "WM-P03", "name": "Dispensing & Weighing Agent", "domain": "WM",
     "framework": "OODA", "depth": "catalog",
     "goal": "Orchestrate accurate, traceable dispensing with FEFO, dual-verification of weights, and 100% material accountability.",
     "triggers": ["Batch order released", "Dispensing request", "FEFO alert"],
     "tools": ["material_availability_tool", "batch_record_query", "raise_deviation",
               "pharma_alert_tool"],
     "escalation": "Weight tolerance failure -> immediate QA + production supervisor",
     "sends_to": ["ME-P02", "EQ-P02"], "receives_from": ["WM-P01", "ME-P01"]},
    {"id": "WM-P04", "name": "Cold Chain Storage Agent", "domain": "WM",
     "framework": "ReAct", "depth": "catalog",
     "goal": "Monitor cold-storage areas in real time, detect temperature excursions, and protect product from storage failures.",
     "triggers": ["Sensor data (5 min)", "Excursion threshold", "Power failure", "Daily min/max log"],
     "tools": ["material_status_update_tool", "pharma_alert_tool", "audit_trail_tool"],
     "escalation": "Major excursion on API or finished product -> QA Director immediately",
     "sends_to": ["QA-P02", "WM-P01", "EQ-P03"], "receives_from": []},
    {"id": "WM-P05", "name": "Material Reconciliation Agent", "domain": "WM",
     "framework": "Reflect-and-Correct", "depth": "catalog",
     "goal": "Perform complete material accountability per batch, verifying yield within limits and closing the material balance.",
     "triggers": ["Batch complete", "Month-end reconciliation", "Yield variance alert"],
     "tools": ["yield_reconciliation_tool", "batch_record_query", "raise_deviation", "pharma_alert_tool"],
     "escalation": "Yield <96% or >105% -> QA + Production Manager",
     "sends_to": ["ME-P04", "QA-P01"], "receives_from": ["ME-P02", "ME-P05"]},

    # -------------------------------------------------- Manufacturing Execution
    {"id": "ME-P01", "name": "Batch Scheduling Agent", "domain": "ME",
     "framework": "Plan-and-Execute", "depth": "full",
     "goal": "Create optimised, resource-constrained batch schedules honouring campaign rules, cleaning constraints, and equipment qualification.",
     "triggers": ["Production plan released", "Batch complete", "Equipment downtime", "Material delay"],
     "tools": ["qualification_status_tool", "cleaning_verification_tool", "material_availability_tool",
               "pharma_alert_tool", "audit_trail_tool"],
     "escalation": "Equipment out-of-qualification with no alternative -> QP + VP Manufacturing",
     "sends_to": ["ME-P02", "WM-P03"], "receives_from": ["SCP-005", "WM-P01", "EQ-P01", "EQ-P04"]},
    {"id": "ME-P02", "name": "Electronic Batch Record (EBR) Agent", "domain": "ME",
     "framework": "OODA", "depth": "full",
     "goal": "Manage the EBR lifecycle from template to step-by-step execution, ensuring contemporaneous, complete, 21 CFR Part 11 records.",
     "triggers": ["Batch order released", "Operator step action", "IPC due", "Record submitted for review"],
     "tools": ["batch_record_query", "cpp_monitor_tool", "ipc_trend_tool", "raise_deviation",
               "pharma_alert_tool"],
     "escalation": "Multiple CPP excursions in same batch -> Production Director + QA",
     "sends_to": ["ME-P04", "ME-P06"], "receives_from": ["ME-P01", "QA-P01"]},
    {"id": "ME-P03", "name": "Process Monitoring Agent (PAT)", "domain": "ME",
     "framework": "ReAct", "depth": "full",
     "goal": "Monitor CPPs/CQAs in real time via PAT, detecting deviations early to enable in-process correction before batch failure.",
     "triggers": ["Step started", "PAT sensor stream", "CPP pre-alarm", "New design space"],
     "tools": ["cpp_monitor_tool", "batch_record_query", "raise_deviation", "pharma_alert_tool"],
     "escalation": "CPP breaches critical limit -> QA + Production Manager immediately",
     "sends_to": ["ME-P04", "ME-P02", "QA-P01"], "receives_from": []},
    {"id": "ME-P04", "name": "Process Deviation Agent", "domain": "ME",
     "framework": "Tree-of-Thought", "depth": "full",
     "goal": "Detect, classify, investigate, and disposition manufacturing deviations before the batch proceeds (GMP-compliant).",
     "triggers": ["CPP excursion", "EBR out-of-spec", "Operator-reported", "Yield OOS", "Equipment malfunction"],
     "tools": ["deviation_context_tool", "cpp_monitor_tool", "raise_deviation", "create_capa",
               "batch_hold_tool", "pharma_alert_tool"],
     "escalation": "CRITICAL deviation -> QA Director + QP within 30 minutes",
     "sends_to": ["QA-P03", "ME-P06"], "receives_from": ["ME-P02", "ME-P03", "WM-P05"]},
    {"id": "ME-P05", "name": "Yield & In-Process Control Agent", "domain": "ME",
     "framework": "OODA", "depth": "full",
     "goal": "Evaluate IPC results at each step, track actual vs theoretical yield, and flag drift before the next step.",
     "triggers": ["IPC result posted", "IPC due", "Step complete", "Yield below warning"],
     "tools": ["ipc_trend_tool", "yield_reconciliation_tool", "batch_record_query", "pharma_alert_tool"],
     "escalation": "IPC failure on critical step -> QA + Production Supervisor",
     "sends_to": ["WM-P05", "ME-P04", "ME-P02"], "receives_from": ["QA-P01"]},
    {"id": "ME-P06", "name": "Batch Disposition Readiness Agent", "domain": "ME",
     "framework": "Reflect-and-Correct", "depth": "full",
     "goal": "Compile the batch documentation package, verify all release requirements, and present a go/no-go RECOMMENDATION to the QP.",
     "triggers": ["Manufacturing complete", "QC final testing complete", "Disposition SLA"],
     "tools": ["batch_disposition_checklist", "batch_record_query", "analytical_result_query",
               "batch_release_report_tool", "qp_notification_tool"],
     "escalation": "Batch release SLA with open items -> QA Director; QP refuses -> VP Quality",
     "sends_to": ["REG-P03"], "receives_from": ["ME-P02", "QA-P01", "ME-P04"]},

    # ------------------------------------------------ Quality Control & Assurance
    {"id": "QA-P01", "name": "QC Testing & LIMS Agent", "domain": "QA",
     "framework": "Reflect-and-Correct", "depth": "full",
     "goal": "Manage QC testing lifecycle from order to approval, validating results vs specification and triggering OOS on failure.",
     "triggers": ["Sample received", "Test order created", "Result posted", "Review SLA"],
     "tools": ["analytical_result_query", "oos_detection_tool", "create_oos_investigation",
               "material_status_update_tool", "pharma_alert_tool"],
     "escalation": "OOS on release test -> immediate QA-P02 investigation trigger",
     "sends_to": ["QA-P02", "ME-P05", "ME-P06"], "receives_from": ["WM-P02"]},
    {"id": "QA-P02", "name": "OOS / OOT Investigation Agent", "domain": "QA",
     "framework": "Tree-of-Thought", "depth": "full",
     "goal": "Lead FDA-2006 compliant OOS/OOT investigations (Phase 1 lab, Phase 2 manufacturing) to a defensible root cause.",
     "triggers": ["OOS flagged by QA-P01", "OOT from QA-P05", "Complaint", "Stability failure"],
     "tools": ["oos_investigation_context", "analytical_result_query", "deviation_context_tool",
               "create_capa", "qp_notification_tool"],
     "escalation": "Confirmed OOS with manufacturing root cause -> QP + VP Quality",
     "sends_to": ["QA-P03", "ME-P06"], "receives_from": ["QA-P01", "QA-P05"]},
    {"id": "QA-P03", "name": "CAPA Management Agent", "domain": "QA",
     "framework": "Tree-of-Thought", "depth": "full",
     "goal": "Drive timely, effective corrective/preventive actions across quality events; verify effectiveness to prevent recurrence.",
     "triggers": ["OOS complete", "Deviation requiring CAPA", "Audit finding", "CAPA due"],
     "tools": ["create_capa", "deviation_context_tool", "report_generator_tool", "pharma_alert_tool"],
     "escalation": "CAPA overdue >14 days -> QA Director; effectiveness failure -> QP",
     "sends_to": ["REG-P03"], "receives_from": ["QA-P02", "ME-P04", "SCP-003", "REG-P01"]},
    {"id": "QA-P04", "name": "Change Control Agent", "domain": "QA",
     "framework": "Reflect-and-Correct", "depth": "full",
     "goal": "Manage risk-based change control for processes, equipment, methods, and facilities; ensure no unauthorised change to validated systems.",
     "triggers": ["Change request", "Regulatory dossier change", "Equipment upgrade", "Deadline"],
     "tools": ["create_change_control_tool", "report_generator_tool", "audit_trail_tool"],
     "escalation": "Major regulatory change without prior approval -> QP + Regulatory Affairs",
     "sends_to": ["EQ-P01", "QA-P03"], "receives_from": ["REG-P03", "EQ-P01"]},
    {"id": "QA-P05", "name": "Analytical Trending & Stability Agent", "domain": "QA",
     "framework": "Generate-Critique-Revise", "depth": "full",
     "goal": "Trend analytical + stability data to detect drift and degradation early, enabling intervention before OOS occurs.",
     "triggers": ["New result posted", "Stability pull", "APQR prep Q4", "Trend warning"],
     "tools": ["oos_detection_tool", "stability_trend_tool", "analytical_result_query",
               "report_generator_tool", "pharma_alert_tool"],
     "escalation": "OOT signal on critical CQA -> QA Director; stability failure -> Regulatory Affairs",
     "sends_to": ["QA-P02", "ME-P06"], "receives_from": ["QA-P01"]},
    {"id": "QA-P06", "name": "MES-LIMS Integration & Data Integrity Agent", "domain": "QA",
     "framework": "Reflect-and-Correct", "depth": "full",
     "goal": "Close the gaps between LIMS, MES, and QMS: reconcile lab results into batch records, catch broken handoffs, and enforce ALCOA+ data integrity across systems.",
     "triggers": ["QC result posted in LIMS", "Batch record closing", "Hourly integrity scan", "Handoff SLA breach"],
     "tools": ["lims_mes_reconciliation_tool", "alcoa_integrity_scan_tool",
               "cross_system_reconciliation_tool", "raise_deviation", "audit_trail_tool"],
     "escalation": "ALCOA+ integrity breach on a GMP record -> QA Director + potential data-integrity deviation",
     "sends_to": ["QA-P02", "QA-P03", "ME-P06"], "receives_from": ["QA-P01", "ME-P02", "ME-P05"]},

    # --------------------------------------------- Equipment & Compliance Mgmt
    {"id": "EQ-P01", "name": "Equipment Qualification Agent", "domain": "EQ",
     "framework": "Plan-and-Execute", "depth": "catalog",
     "goal": "Track IQ/OQ/PQ status of all equipment, schedule re-qualification, and block batches on unqualified equipment.",
     "triggers": ["Qualification expiring (90/60/30d)", "New equipment", "Major maintenance", "Change control"],
     "tools": ["qualification_status_tool", "equipment_status_query", "create_change_control_tool",
               "pharma_alert_tool"],
     "escalation": "Critical equipment qualification expired mid-campaign -> QP + VP Manufacturing",
     "sends_to": ["ME-P01", "EQ-P03"], "receives_from": ["QA-P04", "EQ-P03"]},
    {"id": "EQ-P02", "name": "Calibration Management Agent", "domain": "EQ",
     "framework": "ReAct", "depth": "catalog",
     "goal": "Ensure all GMP instruments are calibrated on schedule with metrological traceability; prevent use of out-of-cal equipment.",
     "triggers": ["Calibration due (30/14/7/1d)", "Outlier result", "New instrument", "Calibration complete"],
     "tools": ["calibration_schedule_tool", "equipment_status_query", "pharma_alert_tool", "audit_trail_tool"],
     "escalation": "Out-of-cal instrument used in release testing -> QA Director + QA-P02",
     "sends_to": ["QA-P01", "QA-P02"], "receives_from": []},
    {"id": "EQ-P03", "name": "Preventive Maintenance Agent", "domain": "EQ",
     "framework": "Plan-and-Execute", "depth": "catalog",
     "goal": "Manage PM to preserve validated equipment state, prevent failures, and minimise batch-schedule impact.",
     "triggers": ["PM due (30/14/3/1d)", "Condition anomaly", "Campaign ending", "Emergency breakdown"],
     "tools": ["pm_schedule_tool", "mtbf_reliability_tool", "create_maintenance_wo", "pharma_alert_tool"],
     "escalation": "Critical PM overdue on key equipment -> QA + VP Manufacturing",
     "sends_to": ["EQ-P01", "EQ-P04"], "receives_from": ["ME-P01"]},
    {"id": "EQ-P04", "name": "Cleaning Verification Agent", "domain": "EQ",
     "framework": "Plan-and-Execute", "depth": "catalog",
     "goal": "Verify equipment cleaning between campaigns against validated procedures and MACO limits before the next batch.",
     "triggers": ["Campaign end/changeover", "Cleaning started", "Verification sample received"],
     "tools": ["cleaning_verification_tool", "equipment_status_query", "raise_deviation", "pharma_alert_tool"],
     "escalation": "Cleaning verification fails twice -> QA Director + process investigation",
     "sends_to": ["ME-P01", "ME-P02"], "receives_from": ["ME-P01"]},
    {"id": "EQ-P05", "name": "Asset Performance Agent", "domain": "EQ",
     "framework": "Generate-Critique-Revise", "depth": "catalog",
     "goal": "Track long-term equipment performance and TCO to identify ageing equipment posing product-quality risk.",
     "triggers": ["Monthly report cycle", "Major failure", "Design-life threshold", "Q3 capital planning"],
     "tools": ["mtbf_reliability_tool", "qualification_status_tool", "report_generator_tool"],
     "escalation": "Equipment posing imminent quality/compliance risk -> VP Manufacturing + QP",
     "sends_to": ["ME-P01", "QA-P04"], "receives_from": ["EQ-P03"]},

    # ---------------------------------------------- EHS, Regulatory & PV
    {"id": "REG-P01", "name": "GMP Compliance Agent", "domain": "REG",
     "framework": "Reflect-and-Correct", "depth": "catalog",
     "goal": "Monitor GMP compliance, SOP currency, training, and audit programmes; maintain inspection readiness at all times.",
     "triggers": ["SOP review due", "Internal audit", "Deviation pattern", "Inspection announced"],
     "tools": ["report_generator_tool", "deviation_context_tool", "pharma_alert_tool", "audit_trail_tool"],
     "escalation": "Critical GMP non-compliance -> QP + VP Quality immediately",
     "sends_to": ["QA-P03", "REG-P03"], "receives_from": ["ME-P04", "QA-P03"]},
    {"id": "REG-P02", "name": "Environmental Monitoring Agent (EM)", "domain": "REG",
     "framework": "ReAct", "depth": "catalog",
     "goal": "Execute and evaluate the EM programme for classified cleanrooms, detecting microbiological and particulate excursions.",
     "triggers": ["EM sample due", "Micro result posted", "Particle alarm", "Batch-linked EM"],
     "tools": ["em_result_query", "raise_deviation", "pharma_alert_tool", "audit_trail_tool"],
     "escalation": "Action level in aseptic filling -> QP + Microbiology Director (immediate)",
     "sends_to": ["QA-P02", "ME-P06", "REG-P01"], "receives_from": []},
    {"id": "REG-P03", "name": "Regulatory Intelligence Agent", "domain": "REG",
     "framework": "Generate-Critique-Revise", "depth": "catalog",
     "goal": "Monitor FDA/EMA/MHRA/ICH actions, assess impact on products, and prepare regulatory responses and submissions.",
     "triggers": ["Daily authority scan", "Guideline update", "Supplier warning letter", "Q4 review"],
     "tools": ["report_generator_tool", "supplier_scorecard_tool", "pharma_alert_tool"],
     "escalation": "FDA Warning Letter to API supplier -> Supply Chain + QP (same day)",
     "sends_to": ["SCP-003", "QA-P04", "QA-P03"], "receives_from": ["REG-P05"]},
    {"id": "REG-P04", "name": "Safety & Occupational Health Agent", "domain": "REG",
     "framework": "ReAct", "depth": "catalog",
     "goal": "Protect employees from chemical/biological/ergonomic hazards (potent APIs, solvents), ensuring OSHA/OEL compliance.",
     "triggers": ["Shift start", "Potent compound handling", "Exposure reading", "Safety incident"],
     "tools": ["pharma_alert_tool", "report_generator_tool", "audit_trail_tool"],
     "escalation": "Confirmed exposure above OEL -> Occupational Health + HR + QP",
     "sends_to": ["REG-P01", "WM-P03"], "receives_from": ["ME-P01"]},
    {"id": "REG-P05", "name": "Pharmacovigilance & Signal Detection Agent", "domain": "REG",
     "framework": "Tree-of-Thought", "depth": "catalog",
     "goal": "Monitor post-market safety data, detect signals via PRR/ROR/IC, and ensure timely ICSR reporting within legal timeframes.",
     "triggers": ["Adverse event received", "Weekly literature search", "PSUR due", "Authority safety query"],
     "tools": ["signal_detection_tool", "report_generator_tool", "qp_notification_tool", "pharma_alert_tool"],
     "escalation": "New serious unexpected signal -> Medical Director + QP + CEO (within 24h)",
     "sends_to": ["REG-P03", "SCP-005"], "receives_from": ["QA-P03"]},
]

AGENTS_BY_ID = {a["id"]: a for a in AGENTS}


def get_agent(agent_id: str) -> dict | None:
    return AGENTS_BY_ID.get(agent_id)


def list_agents() -> list[dict]:
    return AGENTS


def domain_of(agent_id: str) -> dict:
    a = AGENTS_BY_ID.get(agent_id, {})
    return DOMAINS.get(a.get("domain"), {})
